### PR TITLE
Navbar link to homepage added

### LINKED ISSUE #237: add logo to navbar that redirects to homepage

### PR DESCRIPTION
**Pull request by warreprovoost**
Closes #237

### CODE REVIEW

**Review by Vucis — APPROVED** [review]

**Review by AronBuzogany — CHANGES_REQUESTED** [review]
Might be a different issue, but: This doesn't work for me when pressing the home button on the root index "/"

There is a weird border next to the home button:

image

**Comment by warreprovoost** [comment]
> Might be a different issue, but: This doesn't work for me when pressing the home button on the root index "/"
> 
> There is a weird border next to the home button:
> 
I added a language path to many and removed the border

**Review by AronBuzogany — COMMENTED** [review]
For some reason, on your branch, when clicking on other links I get `en-Us` instead of `en`

**Comment by warreprovoost** [comment]
> For some reason, on your branch, when clicking on other links I get `en-Us` instead of `en`

I had that too, i think it is a different issue that is present on the development branch,

**Comment by AronBuzogany** [comment]
> I had that too, i think it is a different issue that is present on the development branch

I tried it on development and there I don't have this issue.
I am also not sure why this issue is present on your branch

**Comment by warreprovoost** [comment]
> I tried it on development and there I don't have this issue. I am also not sure why this issue is present on your branch

I just tested it on development and got the same error, it does not always happen tho

**Comment by AronBuzogany** [comment]
This PR will also Close #231

**Review by AronBuzogany — APPROVED** [review]

**Pull request merged**
