### PR TITLE
Fix en-us bug

### PR DESCRIPTION
**Pull request by Vucis**

### CODE REVIEW

**Comment by Vucis** [comment]
I haven't been able to replicate the bug since the fixes, but maybe test it yourself before approving just in case

**Review by AronBuzogany — CHANGES_REQUESTED** [review]
No problems in URL but if I do 

Login -> click a project on homepage -> errors loading the page -> reload page -> everything fine

**Comment by warreprovoost** [comment]
> No problems in URL but if I do
> 
> Login -> click a project on homepage -> errors loading the page -> reload page -> everything fine

@AronBuzogany I seem to have this problem on development also

**Review by warreprovoost — APPROVED** [review]

**Review by Gerwoud — APPROVED** [review]
:fire:

**Review by AronBuzogany — APPROVED** [review]
Epic 🔥 🚒

**Pull request merged**
